import type { ComplianceRiskReport } from '../types/riskEngine';

/** Demo report for UI development and offline demos */
export const MOCK_COMPLIANCE_RISK_REPORT: ComplianceRiskReport = {
  complianceScore: 72,
  overallRisk: 'HIGH',
  overallRiskLabel: 'HIGH',
  penaltyExposure: {
    min: 15000,
    max: 60000,
    formatted: '₹15,000 - ₹60,000',
  },
  licensesAtRisk: 3,
  businessSector: 'Restaurant / Food Service',
  state: 'Karnataka',
  requiredLicenses: ['FSSAI', 'GST', 'Trade License', 'Fire NOC', 'Shop & Establishment'],
  licenseAssessments: [
    {
      licenseId: 'mock-1',
      licenseType: 'FSSAI',
      licenseNumber: '12345678901234',
      issueDate: '2023-01-15',
      expiryDate: '2025-05-27',
      issuingAuthority: 'FSSAI Karnataka',
      status: 'EXPIRED',
      daysUntilExpiry: -17,
      daysSinceExpiry: 17,
      riskLevel: 'HIGH',
      urgency: 'HIGH',
      estimatedPenalty: { min: 5000, max: 10000, formatted: '₹5,000 - ₹10,000', confidence: 72 },
      recommendedAction: 'Renew FSSAI license immediately on foodlicenseportal.org and pay late fees.',
      legalConsequences: ['Business closure order', 'Seizure of food items'],
      penaltyReasons: ['Operating without valid license', 'Late renewal'],
    },
    {
      licenseId: 'mock-2',
      licenseType: 'Trade License',
      licenseNumber: 'TL-BBMP-2024-8891',
      issueDate: '2024-06-01',
      expiryDate: '2026-06-19',
      issuingAuthority: 'BBMP',
      status: 'EXPIRING_SOON',
      daysUntilExpiry: 6,
      daysSinceExpiry: 0,
      riskLevel: 'CRITICAL',
      urgency: 'CRITICAL',
      estimatedPenalty: { min: 2000, max: 8000, formatted: '₹2,000 - ₹8,000', confidence: 65 },
      recommendedAction: 'Renew Trade License through your local municipal corporation (BBMP/ULB).',
      legalConsequences: ['Premises sealing', 'Daily compounding fines'],
      penaltyReasons: ['Operating without municipal trade license'],
    },
    {
      licenseId: 'mock-3',
      licenseType: 'GST',
      licenseNumber: '29ABCDE1234F1Z5',
      issueDate: '2022-04-10',
      expiryDate: '2027-04-09',
      issuingAuthority: 'GSTN',
      status: 'ACTIVE',
      daysUntilExpiry: 300,
      daysSinceExpiry: 0,
      riskLevel: 'LOW',
      urgency: 'LOW',
      estimatedPenalty: { min: 0, max: 0, formatted: '₹0', confidence: 65 },
      recommendedAction: 'File returns on services.gst.gov.in.',
      legalConsequences: ['GSTIN suspension'],
      penaltyReasons: ['Late GST return filing'],
    },
  ],
  missingLicenses: [
    {
      licenseType: 'Fire NOC',
      risk: 'HIGH',
      potentialImpact: 'Business Closure Risk',
      penaltyEstimate: { min: 10000, max: 100000, formatted: '₹10,000 - ₹1,00,000' },
      recommendedAction: 'Apply for Fire NOC on the official portal immediately.',
      legalConsequences: ['Immediate closure notice', 'Insurance claim invalidation'],
    },
  ],
  expiryRiskSummary: { active: 1, medium: 0, high: 1, critical: 1 },
  auditReport: {
    complianceScore: 72,
    overallRisk: 'HIGH',
    issuesFound: [
      { id: 1, type: 'LICENSE_RISK', licenseType: 'FSSAI', description: 'FSSAI expired 17 days ago', riskLevel: 'HIGH', urgency: 'HIGH', potentialPenalty: '₹5,000 - ₹10,000', potentialConsequence: 'Business closure order' },
      { id: 2, type: 'MISSING_LICENSE', licenseType: 'Fire NOC', description: 'Fire NOC missing', riskLevel: 'HIGH', urgency: 'HIGH', potentialPenalty: '₹10,000 - ₹1,00,000', potentialConsequence: 'Business Closure Risk' },
      { id: 3, type: 'LICENSE_RISK', licenseType: 'Trade License', description: 'Trade License expiring in 6 days', riskLevel: 'CRITICAL', urgency: 'CRITICAL', potentialPenalty: '₹2,000 - ₹8,000', potentialConsequence: 'Premises sealing' },
    ],
    recommendedActions: [
      'Renew FSSAI immediately — expired 17 days ago',
      'Apply for Fire NOC — Business Closure Risk',
      'Renew Trade License before expiry (6 days left)',
    ],
  },
  generatedAt: new Date().toISOString(),
};
